version: "3"
services:
  nginx:
    image: ${NGINX_IMAGE}
    ports:
      - 80:80
      - 443:443
      - 28443:28443
    volumes:
      - "${DEPLOYMENT_ROOT}/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:z"
      - "${DEPLOYMENT_ROOT}/nginx/html:/usr/share/nginx/html:z"
      - "/etc/letsencrypt:/etc/certs:z"
    restart: always
