---
- name: create deployment directory
  file:
    path: '{{ DEPLOYMENT_ROOT }}'
    state: directory
    mode: 0755

- name: copy docker-compose.yml
  copy:
    src: docker-compose.yml
    dest: '{{ DEPLOYMENT_ROOT }}/docker-compose.yml'
    owner: root
    group: root
    mode: 0644

- name: generate .env
  blockinfile:
    path: '{{ DEPLOYMENT_ROOT }}/.env'
    create: yes
    owner: root
    group: root
    mode: 0644
    block: |
      DEPLOYMENT_ROOT={{ DEPLOYMENT_ROOT }}

      NGINX_IMAGE={{ NGINX_IMAGE }}

- name: create nginx directory
  file:
    path: '{{ DEPLOYMENT_ROOT }}/nginx'
    state: directory
    mode: 0755

- name: create nginx conf directory
  file:
    path: '{{ DEPLOYMENT_ROOT }}/nginx/conf'
    state: directory
    mode: 0755

- name: copy nginx.conf
  copy:
    src: nginx/conf/nginx.conf
    dest: '{{ DEPLOYMENT_ROOT }}/nginx/conf/nginx.conf'
    owner: root
    group: root
    mode: 0644

- name: create nginx html directory
  file:
    path: '{{ DEPLOYMENT_ROOT }}/nginx/html'
    state: directory
    mode: 0755

- name: copy index.html
  copy:
    src: nginx/html/index.html
    dest: '{{ DEPLOYMENT_ROOT }}/nginx/html/index.html'
    owner: root
    group: root
    mode: 0644

- name: start docker
  command: /usr/local/bin/docker-compose up -d
  args:
    chdir: '{{ DEPLOYMENT_ROOT }}'
    